# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bf2fb9cc75ab6269e633dabc4de457f79650bda5dcd84a71451f8ec2edc27ced2740de27974038d7e2af4d016ccc607bb31fe610294fa1be06ee623f7d41e71

test:
  secret_key_base: 91ea6c4e968a037306cd94882c055e90a2d5a353a444c9764ee9319735ec7332c78ee4d5052fcf892900f24b0131316cf3064f579250d0116e22569978873321

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
